// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xc.Tonglian.Web;

namespace Xc.Tonglian.Web.Migrations
{
    [DbContext(typeof(TonglianDbContext))]
    [Migration("20210421084047_Customerinit")]
    partial class Customerinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Xc.Tonglian.Web.Models.Domain.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AccountName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AccountNo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Addr")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BicCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CardorBook")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CusId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsDel")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nature")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Province")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Xc.Tonglian.Web.Models.Domain.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Accts")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Areacode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Belongbranch")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Bnfaddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Bnfexpire")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Bnfidno")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Bnfname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Businesskind")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Businessplace")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Buslicense")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Creditcode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Creditcodeexpire")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CtId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Cuskind")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EntityName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Flag")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Holderexpire")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Holderidno")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Holdername")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsDel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Legal")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Legalemail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Legalidexpire")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Legalidno")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Mers")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Organcode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Protocolexpire")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Stafftotal")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Threcertflag")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tlinstcode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tradingplatform")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Website")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Websitecountry")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Xc.Tonglian.Web.Models.Domain.Merchant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AreaCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CusId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsDel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MerName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mtid")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OrganId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("Xc.Tonglian.Web.Models.Domain.Shop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AuthToken")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Categroy")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Exists")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsDel")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Monthamt")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Platform")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Runtime")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Weburl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });
#pragma warning restore 612, 618
        }
    }
}
